---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: my-gangster-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx-nvidia-open
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
    optfix:
      - Mullvad VPN
    install:
      packages:
        - mullvad-vpn

  - type: dnf
    install:
      packages:
        - firefox
        - rclone

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
        install:
          - org.gnome.Loupe
          - md.obsidian.Obsidian
          - com.spotify.Client
          - org.signal.Signal
          - dev.vencord.Vesktop
          - us.zoom.Zoom
          - org.videolan.VLC
          - com.valvesoftware.Steam
          - org.onlyoffice.desktopeditors

  - type: bling
    install:
      - 1password

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

